// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsw8Zp-l7X1tX_KclUJ0RVUTVvv1QNnkY',
    appId: '1:724297011419:web:ce334a57199ebadaabbcfe',
    messagingSenderId: '724297011419',
    projectId: 'med-minder-b8b28',
    authDomain: 'med-minder-b8b28.firebaseapp.com',
    storageBucket: 'med-minder-b8b28.appspot.com',
    measurementId: 'G-5QN3S6TY4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbGe_1u2-WXLDBjH6ALTaOPfNIiA-l5E',
    appId: '1:724297011419:android:57b27005d390ce29abbcfe',
    messagingSenderId: '724297011419',
    projectId: 'med-minder-b8b28',
    storageBucket: 'med-minder-b8b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp46Ip8zpEjTpJQ7U2_eMtO6x8s0AXO1E',
    appId: '1:724297011419:ios:9d25fbe26ebac784abbcfe',
    messagingSenderId: '724297011419',
    projectId: 'med-minder-b8b28',
    storageBucket: 'med-minder-b8b28.appspot.com',
    iosBundleId: 'com.example.medMinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp46Ip8zpEjTpJQ7U2_eMtO6x8s0AXO1E',
    appId: '1:724297011419:ios:1d02995990623e3babbcfe',
    messagingSenderId: '724297011419',
    projectId: 'med-minder-b8b28',
    storageBucket: 'med-minder-b8b28.appspot.com',
    iosBundleId: 'com.example.medMinder.RunnerTests',
  );
}
